# Used during DEV to deploy both DB and Front containers
services:
  frontend:
    #image: hilderoc/ecomweb2
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/


  db:
    #image: hilderoc/ecomdb
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "password"
