apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ecommerce
  labels:
    app: ecommerce
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image:  "{{ .Values.image.frontend.repository}}:{{ .Values.image.frontend.tag}}"
        env:
          - name: DB_HOST
            value: {{ .Release.Name }}-mariadb  #This should match the MariaDB service name
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mariadb-secret
                key: user-db-password
          - name: FEATURE_DARK_MODE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-app-settings
                key: dark_mode
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30 
          periodSeconds: 10 
          timeoutSeconds: 10
          failureThreshold: 3