apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecommerce
spec:
  selector:
    app: ecommerce
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80